AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.log'
    - 'config.ru'
    - 'spec/**/*'
    - 'test/**/*'


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false