AllCops:
  NewCops: enable
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/**/*.rb'
    - '**/*.gemfile'
    - '**/*.rake'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120
