AllCops:
  NewCops: enable
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/**/*.rb'
    - '**/*.gemfile'
    - '**/*.rake'
  Exclude:
    - bin/**

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude: 
   - 'config/**/*.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude: 
  - 'config/environments/*.rb'
