---

name: "[Reek] Code Quality Checks"

on:
  pull_request:
    branches: ['main']

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: .github/gemfiles/code_quality.gemfile
    strategy:
      matrix:
        ruby: ['3.0.2']
    name: styleguide
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Look for code smells
        run: bundle exec reek -c ./.reek.yml app/ lib/

...
